---
# Aggregated linting job, which calls individual linters as reusable workflows.
# This workflow can be extended to include additional linters as needed.
name: Lint

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  pull-requests: write
  issues: write
  statuses: write

jobs:
  validate-pr-title:
    uses: OvertureMaps/workflows/.github/workflows/validate-pr-title.yml@main
